# Generated by Django 3.2.9 on 2021-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dating',
            name='image',
            field=models.ImageField(default='whatever', upload_to='images'),
            preserve_default=False,
        ),
    ]
