# Generated by Django 3.2.9 on 2021-12-07 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_dating_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='dating',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dating.location'),
            preserve_default=False,
        ),
    ]
