# Generated by Django 3.2.9 on 2021-12-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0003_auto_20211207_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='dating',
            name='date',
            field=models.DateField(default='1995-04-08'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dating',
            name='facilitator',
            field=models.ManyToManyField(blank=True, to='dating.Facilitator'),
        ),
    ]
